package com.ekz.ctt.eckctt.mvp.model.entity;


import java.io.Serializable;

public class TUserBloodPressure implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.user_name
     *
     * @mbggenerated
     */
    private String userName;

    public TUserBloodPressure(Integer systolicPressure, Integer diastolicPressure, String createTime) {
        this.systolicPressure = systolicPressure;
        this.diastolicPressure = diastolicPressure;
        this.createTime = createTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.systolic_pressure
     *
     * @mbggenerated
     */
    private Integer systolicPressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.diastolic_pressure
     *
     * @mbggenerated
     */
    private Integer diastolicPressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.pulse_pressure
     *
     * @mbggenerated
     */
    private Integer pulsePressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.suggest
     *
     * @mbggenerated
     */
    private String suggest;
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_blood_pressure.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_blood_pressure
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public TUserBloodPressure(String userName, Integer systolicPressure,
                              Integer diastolicPressure, Integer pulsePressure, String status, String suggest,
                              String createTime, String level) {
        this.userName = userName;
        this.level=level;
        this.systolicPressure = systolicPressure;
        this.diastolicPressure = diastolicPressure;
        this.pulsePressure = pulsePressure;
        this.status = status;
        this.suggest = suggest;
        this.createTime = createTime;
    }


    public TUserBloodPressure(Long id, String userName, Integer systolicPressure, Integer diastolicPressure,
                              Integer pulsePressure, String status, String suggest, String level, String createTime) {
        this.id = id;
        this.userName = userName;
        this.systolicPressure = systolicPressure;
        this.diastolicPressure = diastolicPressure;
        this.pulsePressure = pulsePressure;
        this.status = status;
        this.suggest = suggest;
        this.level = level;
        this.createTime = createTime;
    }


    public TUserBloodPressure() {
    }


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getSystolicPressure() {
        return this.systolicPressure;
    }

    public void setSystolicPressure(Integer systolicPressure) {
        this.systolicPressure = systolicPressure;
    }

    public Integer getDiastolicPressure() {
        return this.diastolicPressure;
    }

    public void setDiastolicPressure(Integer diastolicPressure) {
        this.diastolicPressure = diastolicPressure;
    }

    public Integer getPulsePressure() {
        return this.pulsePressure;
    }

    public void setPulsePressure(Integer pulsePressure) {
        this.pulsePressure = pulsePressure;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSuggest() {
        return this.suggest;
    }

    public void setSuggest(String suggest) {
        this.suggest = suggest;
    }

    public String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    public String getCreateTime2() {
        if (createTime.length()>10){
            String timeStart = createTime.substring(0, 10);
            String timeEnd = createTime.substring(createTime.length() - 8);
            return timeEnd+"\n"+timeStart;
        }
        return this.createTime;
    }


    public String getLevel() {
        return this.level;
    }


    public void setLevel(String level) {
        this.level = level;
    }

    @Override
    public String toString() {
        return "TUserBloodPressure{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", systolicPressure=" + systolicPressure +
                ", diastolicPressure=" + diastolicPressure +
                ", pulsePressure=" + pulsePressure +
                ", status='" + status + '\'' +
                ", suggest='" + suggest + '\'' +
                ", level='" + level + '\'' +
                ", createTime='" + createTime + '\'' +
                '}';
    }
}